export enum CARMASTER_EVENT_TYPES {
  CREDENTIAL_REPORTED = 'CREDENTIAL_REPORTED',
}

export enum CARMASTER_NOTIFICATION_TARGET_TYPES {
  MECHANIC = 'MECHANIC',
  SERVICE = 'SERVICE',
  CREDENTIAL = 'CREDENTIAL',
  SERVICE_REQUEST = 'SERVICE_REQUEST',
}
