export enum HOTSPOT_EVENT_TYPES {
  CLIQUE_UPDATED = 'CLIQUE_UPDATED',
  CLIQUE_DELETED = 'CLIQUE_DELETED',
  NEW_CLIQUE = 'NEW_CLIQUE',
  CLIQUE_MEMBER_REQUEST = 'CLIQUE_MEMBER_REQUEST',
  CLIQUE_MEMBER_CANCEL = 'CLIQUE_MEMBER_CANCEL',
  CLIQUE_MEMBER_ACCEPT = 'CLIQUE_MEMBER_ACCEPT',
  CLIQUE_MEMBER_DECLINE = 'CLIQUE_MEMBER_DECLINE',
  CLIQUE_MEMBER_ADDED = 'CLIQUE_MEMBER_ADDED',
  CLIQUE_MEMBER_REMOVED = 'CLIQUE_MEMBER_REMOVED',
  CLIQUE_MEMBER_LEFT = 'CLIQUE_MEMBER_LEFT',
  NEW_CLIQUE_INTEREST = 'NEW_CLIQUE_INTEREST',
  CLIQUE_UNINTEREST = 'CLIQUE_UNINTEREST',
  NEW_RESOURCE_INTEREST = 'NEW_RESOURCE_INTEREST',
  RESOURCE_UNINTEREST = 'RESOURCE_UNINTEREST',

  NEW_POST_REACTION = 'NEW_POST_REACTION',
  NEW_POST_UNREACTION = 'NEW_POST_UNREACTION',
  NEW_POST_CHANGED_REACTION = 'NEW_POST_CHANGED_REACTION',

  NEW_POST_COMMENT = 'NEW_POST_COMMENT',
  NEW_POST_COMMENT_REACTION = 'NEW_POST_COMMENT_REACTION',
  NEW_POST_COMMENT_UNREACTION = 'NEW_POST_COMMENT_UNREACTION',
  NEW_POST_COMMENT_CHANGED_REACTION = 'NEW_POST_COMMENT_CHANGED_REACTION',

  NEW_POST_COMMENT_REPLY = 'NEW_POST_COMMENT_REPLY',
  NEW_POST_COMMENT_REPLY_REACTION = 'NEW_POST_COMMENT_REPLY_REACTION',
  NEW_POST_COMMENT_REPLY_UNREACTION = 'NEW_POST_COMMENT_REPLY_UNREACTION',
  NEW_POST_COMMENT_REPLY_CHANGED_REACTION = 'NEW_POST_COMMENT_REPLY_CHANGED_REACTION',
}

export enum HOTSPOT_NOTIFICATION_TARGET_TYPES {
  CLIQUE = 'CLIQUE',
  RESOURCE = 'RESOURCE',
  POST = 'POST',
  POST_COMMENT = 'POST_COMMENT',
  POST_COMMENT_REPLY = 'POST_COMMENT_REPLY',
}

export enum HOTSPOT_SUBSCRIPTION_TARGET_ACTIONS {
  
}

export enum HOTSPOT_SUBSCRIPTION_TARGET_ACTIONS_INFO {
  
}

export enum HOTSPOT_RESOURCE_TYPES {
  BOOK = 'BOOK',
  VIDEO = 'VIDEO',
  EVENT = 'EVENT',
  ARTICLE = 'ARTICLE',
  WEBSITE = 'WEBSITE',
  PERSON = 'PERSON',
  OTHER = 'OTHER',
}

export enum NoticeVisibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}