export enum WORLDNEWS_EVENT_TYPES {
  NEW_NEWSPOST_REACTION = 'NEW_NEWSPOST_REACTION',
  NEW_NEWSPOST_UNREACTION = 'NEW_NEWSPOST_UNREACTION',
  NEW_NEWSPOST_CHANGED_REACTION = 'NEW_NEWSPOST_CHANGED_REACTION',

  NEW_NEWSPOST_COMMENT = 'NEW_NEWSPOST_COMMENT',
  NEW_NEWSPOST_COMMENT_REACTION = 'NEW_NEWSPOST_COMMENT_REACTION',
  NEW_NEWSPOST_COMMENT_UNREACTION = 'NEW_NEWSPOST_COMMENT_UNREACTION',
  NEW_NEWSPOST_COMMENT_CHANGED_REACTION = 'NEW_NEWSPOST_COMMENT_CHANGED_REACTION',

  NEW_NEWSPOST_COMMENT_REPLY = 'NEW_NEWSPOST_COMMENT_REPLY',
  NEW_NEWSPOST_COMMENT_REPLY_REACTION = 'NEW_NEWSPOST_COMMENT_REPLY_REACTION',
  NEW_NEWSPOST_COMMENT_REPLY_UNREACTION = 'NEW_NEWSPOST_COMMENT_REPLY_UNREACTION',
  NEW_NEWSPOST_COMMENT_REPLY_CHANGED_REACTION = 'NEW_NEWSPOST_COMMENT_REPLY_CHANGED_REACTION',
}

export enum WORLDNEWS_NOTIFICATION_TARGET_TYPES {
  NEWSPOST = 'NEWSPOST',
  NEWSPOST_COMMENT = 'NEWSPOST_COMMENT',
  NEWSPOST_COMMENT_REPLY = 'NEWSPOST_COMMENT_REPLY',
}

export enum WORLDNEWS_SUBSCRIPTION_TARGET_ACTIONS {
  
}

export enum WORLDNEWS_SUBSCRIPTION_TARGET_ACTIONS_INFO {
  
}
