export enum WORLDNEWS_EVENT_TYPES {
  NEW_NEWS_POST_REACTION = 'NEW_NEWS_POST_REACTION',
  NEW_NEWS_POST_UNREACTION = 'NEW_NEWS_POST_UNREACTION',
  NEW_NEWS_POST_CHANGED_REACTION = 'NEW_NEWS_POST_CHANGED_REACTION',

  NEW_NEWS_POST_COMMENT = 'NEW_NEWS_POST_COMMENT',
  NEW_NEWS_POST_COMMENT_REACTION = 'NEW_NEWS_POST_COMMENT_REACTION',
  NEW_NEWS_POST_COMMENT_UNREACTION = 'NEW_NEWS_POST_COMMENT_UNREACTION',
  NEW_NEWS_POST_COMMENT_CHANGED_REACTION = 'NEW_NEWS_POST_COMMENT_CHANGED_REACTION',

  NEW_NEWS_POST_COMMENT_REPLY = 'NEW_NEWS_POST_COMMENT_REPLY',
  NEW_NEWS_POST_COMMENT_REPLY_REACTION = 'NEW_NEWS_POST_COMMENT_REPLY_REACTION',
  NEW_NEWS_POST_COMMENT_REPLY_UNREACTION = 'NEW_NEWS_POST_COMMENT_REPLY_UNREACTION',
  NEW_NEWS_POST_COMMENT_REPLY_CHANGED_REACTION = 'NEW_NEWS_POST_COMMENT_REPLY_CHANGED_REACTION',
}

export enum WORLDNEWS_NOTIFICATION_TARGET_TYPES {
  NEWS_POST = 'NEWS_POST',
  NEWS_POST_COMMENT = 'NEWS_POST_COMMENT',
  NEWS_POST_COMMENT_REPLY = 'NEWS_POST_COMMENT_REPLY',
}

export enum WORLDNEWS_SUBSCRIPTION_TARGET_ACTIONS {
  
}

export enum WORLDNEWS_SUBSCRIPTION_TARGET_ACTIONS_INFO {
  
}
